import type { Metadata, NextPageContext } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import PrivyProviderWrapper from "@/providers/AuthProvider";
import{ ContextProvider} from '@/contexts/ContextProvider';

import { GoogleAnalytics } from '@next/third-parties/google'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kairos | Hazte Analista",
  description: "Generated by create next app",
  icons: ['/kairos-main.svg']
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
        <GoogleAnalytics
          gaId="G-YB338GCGTW"
        ></GoogleAnalytics>
        <body className={inter.className}>
          <ContextProvider>
            <PrivyProviderWrapper>
              {children}
            </PrivyProviderWrapper>
          </ContextProvider>
        </body>
    </html>
    

  );
}
